# Robot name goes here
robot_car: 
  # default controller
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  gazebo_ros_control:
    pid_gains:
      fr_joint_controller:
        p: 70.0
        i: 0.001
        d: 0.0
      fl_joint_controller:
        p: 70.0
        i: 0.001
        d: 0.0
      rr_wheel_controller:
        p: 70.0
        i: 0.001
        d: 0.0
      rl_wheel_controller:
        p: 70.0
        i: 0.001
        d: 0.0
  # Controller 1
  fr_axle_controller:
    type: effort_controllers/JointPositionController 
    joint: r_axle_joint 
    pid : {p: 1000.0, i: 1.0, d: 10.0} 

  # Controller 2
  fl_axle_controller: 
    type: effort_controllers/JointPositionController 
    joint: l_axle_joint 
    pid : {p: 1000.0, i: 1.0, d: 10.0} 
  
  # Controller 3
  rr_wheel_controller: 
    type: velocity_controllers/JointVelocityController 
    joint: rr_wheel_joint 
    pid : {p: 1000.0, i: 1.0, d: 10.0} 
  # Controller 4
  rl_wheel_controller: 
    type: velocity_controllers/JointVelocityController 
    joint: rl_wheel_joint 
    pid : {p: 1000.0, i: 1.0, d: 10.0}  
 
